### ISSUE TITLE
Test Launched Sites

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#1786]
With the ability of Travis matrices, several test runs can be used to test different configuration of sites. For instance, PHP 7.0, 7.1, and 7.2 could be tested against a new site, the homepage, and the today site in parallel test runs.

The Drupal Extension might do more with Drupal's PHP code than I currently realize, but all Behat tests should be written in the form of how a user interacts with a site and that process will never touch anything other than the UI via a browser.

All that should need to be changed are the exported environmental variables, but paths to the Drupal root are specified in the behat.yml file.

**Comment by alexfinnarn** [comment]
The closed PR ran and passed tests on a Pantheon site: http://dev-ext-test.pantheonsite.io/. For work to be done to test external sites, the test servers would have to have a hole poked. 

Then, some sort of test matrix should be created to run tests on both newly installed and live backups of sites.

```yaml
language: php
php:
  - 7.1
  - 7.0
matrix:
  include:
    - php: 7.1
    env: EXT_SITE=no
  allow_failures:
    - php: 7.0
    env: EXT_SITE=webcentral
```

The PHP 7.0 build runs tests on `www-test.colorado.edu/webcentral` while the PHP 7.1 build runs tests on a newly created site on Travis.

Some sort of enabling of module(s) will need to happen before the test is run unless this would be done in different repos. Ideally, it would be done in the Express repo so every PR has some way of testing live sites.
